### ISSUE TITLE
Understanding: Openapi reference in libvt

### ISSUE THREAD

**Issue by TBSniller** [webosbrew/tv-native-apis#1]
I think these lines: https://github.com/webosbrew/tv-native-apis/blob/51c95a679d9412b59920a11ce926fc42db8a6440/libvt/include/vt/vt_openapi.h#L52
are referencing to another library? Where can I find them?
Furthermore, why these single functions are needed and how do they work together? 

Thanks!

**Comment by mariotaku** [comment]
This repo is providing headers and (fake) libraries for dynamic linking. Those function declarations are actually from your TV.

**Comment by TBSniller** [comment]
So dynamic linking means, that for this example, if the function with exact this name is called, in real the function in the specific library is called? If it is so, where is this thing matched, because I can't see any includes or other stuff related to this.

**Comment by mariotaku** [comment]
Let's say there is `libvt.so.1` in your TV. If one program wants to call it, they will need to link to this library. This project is to create fake libraries like `libvt.so.1` using [source that does nothing](https://github.com/webosbrew/tv-native-apis/blob/main/libvt/src/vt_openapi.c), so programs can be linked against it. When you run the cross compiled program on your TV, it would work then.

For application developers you don't have to care about the details.

**Comment by TBSniller** [comment]
I think this is done. Thank you very much! Explained very good and understoodable.
