### ISSUE TITLE
Libvt

### ISSUE THREAD

**Issue by zlokomatic** [webosbrew/tv-native-apis#6]
Hi,

im trying to get webos-hyperion to run but it didnt work.

So i tried the examples provided in this repo.
With libvt/capture i get:

```
[Capture Sample] window_id=0
[Capture Sample] resource_id=59
[Capture Sample] VT_CreateContext Failed
```

I cant use libvtcapture/capture as my tv got no libvtcapture library.

So can you give me a hint how i can debug libvt or what i can do to get the capture running?

**Comment by mariotaku** [comment]
This libvt is also a black box. I figured out the way to call it by reverse engineering `tvservice` binary on my TV. But it may vary across different regions and firmwares.

**Comment by Informatic** [comment]
For anyone looking at this issue in the future - all high-performance capture development is going on in https://github.com/webosbrew/hyperion-webos now
